project:
  type: website
  render:
    - index.qmd
    - "/modules/**/*.qmd"

website:
  title: "Formations R dispensées au MASA"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - href: calendrier/calendrier.html
        text: Calendrier
      - href: replays/replays.html
        text: Replays
      - icon: github
        href: https://github.com/SSM-Agriculture/site-formations-R
    background: "#008000"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters:
   - include-code-files

